### ISSUE TITLE
Mongo extensions (aggregation) support

### ISSUE THREAD

**Issue by zvictor** [arunoda/meteor-smart-collections#10]
I am migrating my application to use Smart Collections and I faced the lack of aggregation support which I had already overcome using a snippet based on [meteor-mongo-extensions](https://github.com/jhoxray/meteor-mongo-extensions), so I decided to adapt this extension to work with Smart Collection.

My problem is that it was too easy to do I am afraid I am missing something else, so I created this topic to discuss this matter. Please, tell me if my thought is right.
- _Mongo extensions_ seems to create a dummy collection to deal with the desired operations, and these operations seem to me that they do not need to use smart collections because the operations are volatile, are returned just in memory,  except for `mapReduce` that saves its result in the db and should be `opLog` compliant.
- Considering the above, just linking `Meteor.SmartCollection` to the `distinct` and `aggregate` functions that use regular dummy collections should be enough.
- For the `mapReduce` we have 2 situations.
  - We can also bind the function as we did above, and then our "mapReduce created collections" won't be shared across mongodb instances, but will be accessible by the node process who called the function. [That would be particularly enough for me, because I delete the collection after some processing]
  - We can instantiate the dummy collection as a smart one instead of a regular one for this operation.

Here my is [gist](https://gist.github.com/zvictor/6166443) that just binds the smart collections to dummy regular collections.

**Comment by arunoda** [comment]
I think the the code in the gist is fine. Since we are talking to the same DB, you don't need to go with SmartCollection's mongo adapter.

I also think mapReduce returns the collection name as the result. And You can use SmartCollections to bring back the result to the client/server.

**Comment by zvictor** [comment]
Excelent! =D

> I also think mapReduce returns the collection name as the result. And You can use SmartCollections to bring back the result to the client/server.

The data of the created collection will be propagated across mongo instances?

**Comment by arunoda** [comment]
Are you using multiple mongos? I'm not sure about it. 

If uses a replSet it should be, If sharded hope not.

**Comment by zvictor** [comment]
Whatever we define mapReduce it has a big issue to overcome: jhoxray/meteor-mongo-extensions#4
