### ISSUE TITLE
Client not receiving updates made through server call.

### ISSUE THREAD

**Issue by thedracle** [arunoda/meteor-smart-collections#12]
I create a record via Minimongo, it gets placed in the database:

Using mongo Directly:
db.calls.find({ended:false})
{ "participants" : [    {   "_id" : "f58785da-7ed2-477f-bfa8-816f06987938", "role" : "call_owner",  "state" : "on_call" },  {   "_id" : "oCgsHB9jhptbEKucr",    "role" : "care_recipient",  "state" : "waiting" } ], "start_time" : ISODate("2013-08-13T19:53:55.709Z"), "ended" : false, "room_id" : "jT7dQZ6Rhu4KqX8Sj", "show_video" : true, "show_self_view" : false, "on_hold" : false, "_id" : "LmxeZJDm6N3KqgCfq" }

From Minimongo:
Calls.find().fetch()[0]
Object {_id: "LmxeZJDm6N3KqgCfq", participants: Array[2], start_time: Tue Aug 13 2013 13:53:55 GMT-0600 (MDT), ended: false, room_id: "jT7dQZ6Rhu4KqX8Sj"…}

I make a backend call where this record is updated:

Calls.update({'room_id': body.RoomId, 'participants._id': body.UserId, ended: false}, {$set: {'participants.$.state': 'hang_up', ended: true, end_time: new Date()}}, {multi: true});

The client data doesn't ever get invalidated/updated however.

As viewed from mongo:
 db.calls.find({_id:'LmxeZJDm6N3KqgCfq'})
{ "_id" : "LmxeZJDm6N3KqgCfq", "answered" : true, "end_time" : ISODate("2013-08-13T19:54:36.322Z"), "ended" : true, "on_hold" : false, "participants" : [   {   "_id" : "f58785da-7ed2-477f-bfa8-816f06987938",     "role" : "call_owner",  "state" : "hang_up" },  {   "_id" : "oCgsHB9jhptbEKucr",    "role" : "care_recipient",  "state" : "on_call" } ], "room_id" : "jT7dQZ6Rhu4KqX8Sj", "show_self_view" : false, "show_video" : true, "start_time" : ISODate("2013-08-13T19:53:55.709Z") }

And from minimongo:
Calls.find().fetch()[0]
Object {_id: "LmxeZJDm6N3KqgCfq", participants: Array[2], start_time: Tue Aug 13 2013 13:53:55 GMT-0600 (MDT), ended: false, room_id: "jT7dQZ6Rhu4KqX8Sj"…}

As you can see Minimongo still registers the object as having ended as false, where as the database directly has it set to 'true'.

**Comment by arunoda** [comment]
This is a bug in smart-collections right now. I've scheduled to fix this today. If you use [oplog](http://meteorhacks.com/lets-scale-meteor.html) with smart-collections this problem will be gone.

See this as a reference: (from an internal discussion)

> For update-by-selector... I'm not actually convinced that your code is
> correct. It looks like it re-runs the query and processes everything
> which matches the query.  But you need to process all the documents
> that matched the selector _at the time of the update_, not _after the
> update_.  This is a race condition, or in fact worse:  for
> foo.update({x: {$mod: [2, 0]}}, {$inc: {x: 1}}, {multi: true})  it
> will try to process all the even elements... and _none_ of the
> matching elements will be even any more!  Am I missing something here?
>  And I'm not sure I see a way to fix this without doing something like
> what remove-by-selector does: re-running all the queries.  Which is
> practically the same as what the current mongo-livedata code does
> (though at least your code just picks the right fields instead of
> doing a complex diff).

**Comment by arunoda** [comment]
This issue is fixed in `0.2.12`. Try updating smart collections.
