### ISSUE TITLE
0.3.0

### ISSUE THREAD

**Issue by arunoda** [arunoda/meteor-smart-collections#15]
Make it compatible with Meteor.Collection.
Apply recommendations from David Glasser.

**Comment by richieb** [comment]
Great. Keep up the excellent work, Mate.

**Comment by arunoda** [comment]
Hey. Sorry for this.
This meant to be an milestone, so I deleted it.

Check here:
https://github.com/arunoda/meteor-smart-collections/issues/milestones

On Tue, Aug 20, 2013 at 6:48 AM, Richard notifications@github.com wrote:

> Great. Keep up the excellent work, Mate.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/15#issuecomment-22916573
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
