### ISSUE TITLE
Field filtering support

### ISSUE THREAD

**Issue by arunoda** [arunoda/meteor-smart-collections#16]
We need to filter fields in the changes too.

**Comment by richieb** [comment]
No problem, so just this last item left. Still great! :)

**Comment by arunoda** [comment]
No, some more to added. But they are minor issues. :)

**Comment by richieb** [comment]
Okay, good to know.

**Comment by arunoda** [comment]
added in: 5471d877307ed3712bee8caf402f8d57a8b5abbb
Published as version `0.2.22`
