### ISSUE TITLE
multiple observeChanges() in a cursor

### ISSUE THREAD

**Issue by arunoda** [arunoda/meteor-smart-collections#19]
Currently there is only one observeChanges() can be called for a single cursor. 

I've not checked with how Meteor.Collection works with this. If someone has use this? just tell me how it works.
- When you call second `observeChanges` does it reset the cursor again?  
- Is new `observeChanges` hooks also get the initial docs list too, or only the changes

cc @glasser

**Comment by glasser** [comment]
The state for the second observeChanges is entirely separate from the first (and from whatever may be going on with a forEach or something on the cursor).

**Comment by arunoda** [comment]
Got it.

I'll be equal to creating a new cursor and observing it again.

**Comment by arunoda** [comment]
added with 0.3.x
