### ISSUE TITLE
Collection _id Migration

### ISSUE THREAD

**Issue by digilord** [arunoda/meteor-smart-collections#27]
How do I ensure that I have the correct _id on my collections when I migrate the data from the meteor collection to using smart collections?

**Comment by arunoda** [comment]
Sc only supports string bases _ids. If your db has string based ids it will
work.

On Wednesday, September 4, 2013, D. Allen Morrigan wrote:

> How do I ensure that I have the correct _id on my collections when I
> migrate the data from the meteor collection to using smart collections?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/27
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
Hope I can close this.
