### ISSUE TITLE
Dropping a table does not update the client

### ISSUE THREAD

**Issue by EricTheMagician** [arunoda/meteor-smart-collections#3]
When dropping all entries in a table directly from the mongo console/terminal (from meteor mongo), the client's database is not cleared.

**Comment by arunoda** [comment]
Yes. This does not work until, we integrating Mongo Oplog. Starting next week.

**Comment by EricTheMagician** [comment]
I didn't think that through all the way when I posed this issue.
I thought it was already implemented.

**Comment by arunoda** [comment]
That's fine keep this opened, and other can see it.
I could, but I need to find major bugs before going into that:)

On Sun, Jul 21, 2013 at 3:52 AM, thejinx0r notifications@github.com wrote:

> I didn't think that through all the way when I posed this issue.
> I thought it was already implemented.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/3#issuecomment-21301490
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arunoda** [comment]
Now this is supported with Oplog integration.
See for oplog integration: [Scaling Meteor](http://meteorhacks.com/lets-scale-meteor.html) with MongoDB Oplog
