### ISSUE TITLE
MongoDB oplog setup and settings for SmartCollections

### ISSUE THREAD

**Issue by arc41t3ct** [arunoda/meteor-smart-collections#40]
SmartCollections uses oplog for finding changes. I have setup oplog by adding the right configuration to /etc/mongodb.conf and is called rs0. How do get SmartCollection to watch the oplog. Or what oplog settings to I need for SmartCollections to recognize it? What is the process of SmartCollections recognizing the oplog?

**Comment by arc41t3ct** [comment]
I need this to work because I am pushing data in to MongoDB directly but do not see the changes reactively on the Client-Side.

**Comment by arunoda** [comment]
Refer this - http://meteorhacks.com/lets-scale-meteor.html

On Wed, Nov 20, 2013 at 8:02 PM, Andre Honsberg notifications@github.comwrote:

> I need this to work because I am pushing data in to MongoDB directly but
> do not see the changes reactively on the Client-Side.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/40#issuecomment-28893332
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by arc41t3ct** [comment]
Ah the missing key... Thanks
