### ISSUE TITLE
$geoWithin operator support

### ISSUE THREAD

**Issue by bojan88** [arunoda/meteor-smart-collections#43]
Hello,

Is $geoWithin or at least deprecated $within operator supported?

With SmartCollection I'm getting "Exception from sub PRhpASkNubaoSaWz5 Error: Unrecognized operator: $geoWithin". With Meteor Collections it works fine (both $within and $geoWithin)

**Comment by arunoda** [comment]
see: https://github.com/arunoda/meteor-smart-collections/issues/23
