### ISSUE TITLE
Collection methods return empty array, IE fetch(), forEach(), etc...

### ISSUE THREAD

**Issue by rcorral** [arunoda/meteor-smart-collections#46]
I'm declaring a collection like so:

```
Maps = new Meteor.SmartCollection('maps');
```

This file is location at:
/collections/ideas.js

Then I'm executing this function when the page loads:

```
Template.maps.rendered = function(){
    console.log(Maps.find({}).fetch());
}
```

The result is an empty array that gets logged to the console. If I execute the same function after the page has loaded, it returns a populated array.

I'm using the latest version v0.3.23

**Comment by arunoda** [comment]
This is the expected behaviour of Meteor. Run that code inside Deps.autorun

On Friday, December 6, 2013, Rafael Corral wrote:

> I'm declaring a collection like so:
> 
> Maps = new Meteor.SmartCollection('maps');
> 
> This file is location at:
> /collections/ideas.js
> 
> Then I'm executing this function when the page loads:
> 
> Template.maps.rendered = function(){
>     console.log(Maps.find({}).fetch());
> }
> 
> The result is an empty array that gets logged to the console. If I execute
> the same function after the page has loaded, it returns a populated array.
> 
> I'm using the latest version v0.3.23
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/46
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by rcorral** [comment]
Thank you :)

For the record, this helped me out too:
http://stackoverflow.com/questions/20209534/meteor-js-collection-empty-on-client#answer-20240047
