### ISSUE TITLE
Aggregate SmartCollection?

### ISSUE THREAD

**Issue by luciuz** [arunoda/meteor-smart-collections#47]
https://github.com/meteor/meteor/pull/644 doesn't work with SmartCollections. =\

**Comment by arunoda** [comment]
You don't need SmartCollections for that. Use as it says. It deals with the
direct mongo commands.

On Thursday, January 9, 2014, Luciuz wrote:

> meteor/meteor#644 https://github.com/meteor/meteor/pull/644 doesn't
> work with SmartCollections. =\
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/47
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda

**Comment by luciuz** [comment]
Teach me how

**Comment by luciuz** [comment]
-.-

**Comment by luciuz** [comment]
ANSWER:

```
var path = Npm.require('path');
var Future = Npm.require(path.join('fibers', 'future'));

Meteor.startup(function () {
  Userdata.aggregate = function(pipeline) {
    var self = this;

    var future = new Future;
    self._collection.aggregate(pipeline, function(err, result) {
      if (err) {
        future.throw(err);
        return;
      }
      future.return([true, result]);
    });

    var result = future.wait();
    if (!result[0])
      throw result[1];

    return result[1];
  };

});

Meteor.methods({
  info: function() {
    return Userdata.aggregate([
      //some stuff
    ]);
  }
});
```
