### ISSUE TITLE
Update to Meteor 0.7.1.1

### ISSUE THREAD

**Issue by Lepozepo** [arunoda/meteor-smart-collections#49]
Hi, just updated to the latest version of meteor, apparently subscribing to a smart collection is causing this issue:

![screen shot 2014-02-25 at 12 28 53 am](https://f.cloud.github.com/assets/2302110/2255503/f21a3b98-9df6-11e3-90f9-8983081b5def.png)

Awkwardly enough that doesn't happen when the collection is a Collection2 Smart collection. Is there an easy fix for this?

Thank you

**Comment by Lepozepo** [comment]
Just read the changelog on Collection2, is Smart Collections deprecating?

**Comment by arunoda** [comment]
Yes. Since Meteor.Collection now has most of the smart-collections features and its much stable.

**Comment by Lepozepo** [comment]
Excellent, thank you
