### ISSUE TITLE
Is smart-collections compatible with Meteor 0.7.1.2?

### ISSUE THREAD

**Issue by luciuz** [arunoda/meteor-smart-collections#51]
Hello

Here the problem is:

W20140319-00:23:38.627(4)? (STDERR) } has no method '_compileSelector'
W20140319-00:23:38.627(4)? (STDERR)     at new Query (packages/smart-collections/lib/query.js:8)
W20140319-00:23:38.628(4)? (STDERR)     at Invalidator.initiateQuery (packages/smart-collections/lib/invalidator.js:55)
W20140319-00:23:38.628(4)? (STDERR)     at SmartCollection.find (packages/smart-collections/lib/server_collection.js:83)
W20140319-00:23:38.629(4)? (STDERR)     at Meteor.publish.Dictionary.find.lang (app/lib/common.js:69:22)
W20140319-00:23:38.629(4)? (STDERR)     at /home/v/local/build/programs/server/boot.js:159:61
W20140319-00:23:38.630(4)? (STDERR)     at Array.forEach (native)
W20140319-00:23:38.630(4)? (STDERR)     at Function._.each._.forEach (/home/v/.meteor/tools/f3947a4651/lib/node_modules/underscore/underscore.js:79:11)
W20140319-00:23:38.631(4)? (STDERR)     at /home/v/local/build/programs/server/boot.js:159:5

**Comment by arunoda** [comment]
Nope. There is no reason to use SmartCollection anymore. Meteor 0.7.x (specially 0.7.2) has the same performance.

**Comment by luciuz** [comment]
Okay. it's all that I want to know.

**Comment by Samsy** [comment]
It should be good idea to warn Meteor user that it is not useful anymore to use smart collection.
I mean in official website or something
I tried for a day to install it for 0.7.2 after reading this post !

**Comment by arunoda** [comment]
I just update readme and all the blogs related.
Okay adding a warning message to the package is also a good idea.

On Wednesday, March 26, 2014, Honigstein Samuel notifications@github.com
wrote:

> It should be good to warn Meteor user than it is not useful anymore to use
> smart collection.
> 
> I tried for a day to install it for 0.7.2 after reading this post !
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/arunoda/meteor-smart-collections/issues/51#issuecomment-38633663
> .

## 

---

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
