### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by hareshlanover** [arunoda/meteor-smart-collections#56]
The atmosphere seems to be missing binary build. When I try to add package. I'm seeing:

$ meteor add arunoda:smart-collections
=> Errors while adding packages:           

While checking for arunoda:smart-collections@0.4.9
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by arunoda** [comment]
Do not use this project.
See: https://github.com/arunoda/meteor-smart-collections#this-is-a-archived-project
